[package]
name = "maximized"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arr_macro = "0.1"
borsh = "0.9"
solana-program = "1.7"
